### ISSUE TITLE
MethodBodyReader.GetInstructions throws NRE

### ISSUE THREAD

**Issue by FrodoOf9Fingers** [pardeike/Harmony#43] opened 2017-09-25 05:03 UTC
Modding RimWorld, this code throws a Null Reference Exception:

```
    [HarmonyPatch(typeof(PathFinder), "FindPath", new Type[] { typeof(IntVec3), typeof(LocalTargetInfo), typeof(TraverseParms), typeof(PathEndMode) })]
    static class ReversePatch
    {
        [HarmonyTranspiler]
        static IEnumerable<CodeInstruction> copyCode(MethodBase original, IEnumerable<CodeInstruction> instructions)
        {
            MethodBase mb = typeof(FunctionHolders).GetMethod("original");
			
			List<CodeInstruction> codeInstructions = new List<CodeInstruction>();
            foreach (ILInstruction Ili in MethodBodyReader.GetInstructions(method))
            {
                codeInstructions.Add(Ili.GetCodeInstruction());
            }
            return codeInstructions;
        }
	}
```
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Harmony.ILCopying.MethodBodyReader.ReadOperand (Harmony.ILCopying.ILInstruction instruction) [0x00000] in <filename unknown>:0 
  at Harmony.ILCopying.MethodBodyReader.ReadInstructions () [0x00000] in <filename unknown>:0 
  at Harmony.ILCopying.MethodBodyReader.GetInstructions (System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0 
  at _9thFingerThreadingMod.ReversePatch.copyCode (System.Reflection.MethodBase original, IEnumerable`1 instructions) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
```
 
I don't have a debugger available atm, but I'm pretty sure it is because the "variables" variable is never set (as the DeclareVariables function is never called, and there's no generator to even use) when calling MethodBodyReader.GetInstructions, and that variable is referenced in two cases inside of ReadOperand: case OperandType.ShortInlineVar and case OperandType.InlineVar:

**Comment by pardeike** [comment] 2017-09-25 05:14
Duplicate of https://github.com/pardeike/Harmony/issues/22

**Closed by pardeike** 2017-09-25 05:14 UTC
