### ISSUE TITLE
KeyNotFoundException trying to unpatch method with __state

### ISSUE THREAD

**Issue by alexb5dh** [pardeike/Harmony#152] opened 2019-01-28 18:50 UTC
I'm getting `KeyNotFoundException` when trying to remove patch having `__state` variable:
```
Unhandled Exception: System.Exception: Exception from HarmonyInstance "patch" ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Harmony12.MethodPatcher.EmitCallParameter(ILGenerator il, MethodBase original, MethodInfo patch, Dictionary`2 variables, Boolean allowFirsParamPassthrough)
   at Harmony12.MethodPatcher.<>c__DisplayClass20_0.<AddPostfixes>b__1(MethodInfo fix)
   at Harmony12.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at Harmony12.MethodPatcher.AddPostfixes(ILGenerator il, MethodBase original, List`1 postfixes, Dictionary`2 variables, Boolean passthroughPatches)
   at Harmony12.MethodPatcher.CreatePatchedMethod(MethodBase original, String harmonyInstanceID, List`1 prefixes, List`1 postfixes, List`1 transpilers)
   --- End of inner exception stack trace ---
   at Harmony12.MethodPatcher.CreatePatchedMethod(MethodBase original, String harmonyInstanceID, List`1 prefixes, List`1 postfixes, List`1 transpilers)
   at Harmony12.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo, String instanceID)
   at Harmony12.PatchProcessor.Unpatch(MethodInfo patch)
   at Harmony12.HarmonyInstance.Unpatch(MethodBase original, MethodInfo patch)
   at Harmony12.HarmonyInstance.<>c__DisplayClass11_1.<UnpatchAll>b__1(Patch patchInfo)
   at Harmony12.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at Harmony12.CollectionExtensions.DoIf[T](IEnumerable`1 sequence, Func`2 condition, Action`1 action)
   at Harmony12.HarmonyInstance.UnpatchAll(String harmonyID)
   at ConsoleTest.Program.Main()
```

Here's a code to reproduce:
```
[HarmonyPatch(typeof(object), "ToString")]
public static class ObjectToStringPatch
{
    public static void Prefix(out object __state)
    {
        __state = null;
    }

    public static void Postfix(int __state)
    {

    }
}

class Program
{
    static void Main()
    {
        HarmonyInstance.Create("patch").PatchAll();
        HarmonyInstance.Create("patch").UnpatchAll("patch");
    }
}
```

Version 1.2.1 from Nuget

**Comment by pardeike** [comment] 2019-01-28 22:08
Just debugged it. The problem is the order of things. The Unpatch all will remove first the Prefix and then the Postfix. As soon as the Prefix is removed, the method is redone, this time with only the postfix. Every patch (removing a patch is just repatching with one patch less) does this.

Try it, just comment out the Prefix in your code above and try to run the code without UnpatchAll. You will get the same key not found exception because the state is never defined. The workaround is to unpatch the Postfix manually first before running UnpatchAll.

In 2.0, I will make sure an orphaned `__state` in a postfix will always receive `null` instead of failing.

**Comment by pardeike** [comment] 2019-01-29 18:19
Fixed in latest master

**Closed by pardeike** 2019-01-29 18:19 UTC
Labels: bug
