### ISSUE TITLE
Patches stop working after some iterations from cold start, Centos

### ISSUE THREAD

**Issue by Fasjeit** [pardeike/Harmony#526] opened 2023-04-20 08:02 UTC
### **Description**

When executing the detoured method multiple times, we have observed that the patches eventually stop working and the original methods are called instead (and can be walked into using debugger). 

This behavior has been observed in some patches, both methods and constructors, while others seem to work fine.

**Environment** - Harmony 2.2.2, CentOS-like os (linux), dotnet 6 sdk and runtime, compiled both as debug and release.

### **To reproduce**

Code published using `dotnet publish --self-contained -c Debug -r linux-x64`

**Target method**: `System.Security.Cryptography.X509Certificates.get_PublicKey`

**Patch method** (returns null and prints a string):
```csharp
[HarmonyPatch(typeof(PublicKey), "get_Key")]
static class Patch04
{
    public static bool Prefix(PublicKey __instance, ref AsymmetricAlgorithm __result)
    {
        Console.WriteLine("Patched");
        __result = null;
        return false;
    }

    public static void Postfix()
    {
        return;
    }
}
```

**Main**:
```csharp
var harmony = new Harmony("Buggy");
var assembly = Assembly.GetExecutingAssembly();
harmony.PatchAll(assembly);

for (int i = 0; i < 1000; i++)
{
    Console.WriteLine(i);
    var pk = new PublicKey(RSA.Create());
    var key = pk.Key;
    if (key != null)
    {
        // should not be here when patch is active
        throw new Exception();
    }
}
```

**Expected behavior**: No exception thrown

**Current behavior**: exception after ~32 iterations.

The bug **does not** reproduce using Windows or Debian-like os.

### **Is it just an inlining (or more like runtime re-compilation/re-loading)?**
It seems like an inlining problem, but we're still able to step into the original method after the patch is gone, which should not be possible if the method was inlined.

**Screenshots**
Stack trace and debugger, when patch is gone after ~30 iterations. Looks like no inlining involved.
![img](https://user-images.githubusercontent.com/15075638/233294544-ded6a337-e04e-4178-9749-f4d098c9735a.png)

We've also performed a test where we run some iterations before patching the method, and the bug no longer reproduces in this case.

```csharp
// pre heat to trigger possible runtime optimizations
for (int i = 0; i < 100; i++)
{
    Console.WriteLine(i);
    var pk = new PublicKey(RSA.Create());
    var key = pk.Key;
}

Console.WriteLine("Init done");

// now make some patches
var harmony = new Harmony("Buggy");
var assembly = Assembly.GetExecutingAssembly();
harmony.PatchAll(assembly);

// no exception this time!
for (int i = 0; i < 1000; i++)
{
    Console.WriteLine(i);
    var pk = new PublicKey(RSA.Create());
    var key = pk.Key;
    if (key != null)
    {
        throw new Exception();
    }
}
```

We suspect that after some iterations, the runtime may decide to "re-compile" or re-load the IL code for some methods, which restores them to their initial state and throws away the patches.

**Do you have any hints on how we can prevent this behavior?**

**Comment by Fasjeit** [comment] 2023-04-20 10:36
Update - looks like [Tiered compilation](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/compilation#tiered-compilation) is here to be blamed. 

Disabling it with 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>

</Project>
```

in xml seems to resolve the issue with the example above, but it needs a little bit more testing.

I'll keep the issue open for some time, if you wouldn't mind.

**Comment by pardeike** [comment] 2023-04-20 11:38
Please test with prerelease of Harmony 2.3

**Comment by Fasjeit** [comment] 2023-04-20 13:07
Same result with 2.3 from master.

**Comment by Windows10CE** [comment] 2023-04-20 20:27
I could not reproduce this on Arch Linux, nor in a Docker container for CentOS 6, 7, or 8. Could you say more about exactly what environment you're running in? This is such a weird issue that it's almost impossible to guess what the cause is without a consistent repro to test against.

**Comment by Fasjeit** [comment] 2023-04-21 04:16
@Windows10CE We are reproducing it with Fedora 38 VM installed from iso from the site, no containers. Customers also reported it with Centos 7, and some other red hat-like OS (asked them for an exact list).

The project is published on Windows 10 with `dotnet publish --self-contained -c Debug -r linux-x64`, copied to VM, and run on Fedora by executing the elf file.

If you need I can send a link to the entire VMWare VM file.

**Comment by pardeike** [comment] 2023-07-02 22:58
I've fixed a couple of Ubuntu/Mono related bugs today. Could you test my latest master one more time?

**Comment by Fasjeit** [comment] 2023-07-03 05:50
Sure, I'll check again.

Also this behavior was reproduced (using the older version) in Windows and Ubuntu, but it needs a much more time to trigger. So it is not just Centos.

**Comment by Fasjeit** [comment] 2023-07-03 08:23
No longer reproduce it with Fedora Workstation 38! ~10k iterations are working fine.

Just curious, how is Tiered compilation is being dealt with? Is it some kind of runtime checks or any other way to disable/control it during patching?

**Comment by pardeike** [comment] 2023-07-03 13:15
That is part of the low level MonoMod Core dependency. I suggest you ask it there or on the Harmony discord. I close this issue for now.

**Closed by pardeike** 2023-07-03 13:15 UTC
Labels: cannot reproduce
