### ISSUE TITLE
Provide a way to call back to the original method without recursive calling to patch method

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [pardeike/Harmony#177] opened 2019-04-19 02:08 UTC
Is there anyway to do it? I know I can just let the program run from prefix method, to original method and finally to postfix method. But having to explicitly write prefix method and postfix method is kind of cumbersome, and I cannot make any more complex logic. I think of a way like this:
```csharp
// the same Prefix for every methods
static bool Prefix() {
   return false;
}
static void Postfix(MethodInfo __reentrantMethod, ref int someParam, TargetClass __instance, ref ResultType __result) {
    // callback to original method without triggering any Prefix and Postfix
   __result = (ResultType)__reentrantMethod.Invoke(__instance, new object[] { someParam });
}
```

Additionally, can Harmony handle multithreading, I mean, there are cases when the target method is being run and I patch it?

**Comment by pardeike** [comment] 2019-04-19 06:21
What’s the use case and how would this work with multiple mods?

**Comment by pardeike** [comment] 2019-04-19 06:22
Possible duplicate of #41

**Comment by Meigyoku-Thmn** [comment] 2019-04-19 06:46
In my use case, I want to hook/patch a lot of methods (right now I want to patch 12 methods) in a game that doesn't support modding. Implementing Prefix and Postfix for every single methods will unnecessary bloat my code. It had to be a better way.
Having a reentrant method also allows me to call back to the original method more than one time without having to recursively call, I think this will be useful sometime.

**Comment by pardeike** [comment] 2019-04-19 10:06
Are you aware that patch methods (prefix, postfix or transpiler) can be factory methods? Just let them return a DynamicMethod which is executed instead of the method itself. Add that you can inject the original with __originalMethod and use it to build your dynamic prefix/ postfixes. 

Reverse patching is the concept of piping the original IL through a transpiler and replace a stub message you have in your own code. The stub would need to have the same signature as the original (assuming an identity transpiler) or a different signature if the transpiler results in a subset or modification of the original. A very powerful concept I have yet to implement and one that needs refinement regarding the choice of “original” with valid cases being: real original, patches original or other edge cases.

**Comment by Meigyoku-Thmn** [comment] 2019-04-19 16:05
Well, look like I found a way:
```csharp
namespace Test {
   public class Test {
      public static int Add(int a, int b) {
         return a + b;
      }
   }
   public class Program {
      static bool Prefix() {
         return false;
      }
      static DynamicMethod reentrantMethod;
      static void Add(int a, int b, ref int __result) {
         __result = (int)reentrantMethod.Invoke(null, new object[] { 3, 4 });
      }
      static void Main(string[] args) {
         var harmony = HarmonyInstance.Create("com.company.project.product");
         var original = AccessTools.Method(typeof(Test), "Add");
         var prefix = AccessTools.Method(typeof(Program), "Prefix");
         var postfix = AccessTools.Method(typeof(Program), "Add");
         reentrantMethod = harmony.Patch(original);
         harmony.Patch(original, new HarmonyMethod(prefix), new HarmonyMethod(postfix));
         Console.WriteLine(Test.Add(1, 2));
      }
   }
}
```
It turns out the Patch method returns a DynamicMethod object, if I just pass the original method into it, it will create a copy of the original method :D

**Closed** 2019-05-04 10:40 UTC
