### ISSUE TITLE
Error: Wrong MethodAttributes or CallingConventions for DynamicMethod.

### ISSUE THREAD

**Issue by Hooch180** [pardeike/Harmony#76] opened 2018-04-15 11:50 UTC
Hello,
I'm getting this exception when trying to create a hook.
Error happens when invoking harmony.Patch(...) method.
This is my code (.NET 4.5.2).

```
        private void InitializeSaveHook()
        {
            HarmonyInstance harmony = HarmonyInstance.Create("pl.itmk.BizTalkFileFormatter.vsix");
            MethodInfo originalSave = typeof(Microsoft.BizTalk.Mapper.OM.Map).GetMethod("Save");
            MethodInfo prefixSave = AccessTools.Method(typeof(VSPackage), "patchPrefixSave");
            MethodInfo postfixSave = AccessTools.Method(typeof(VSPackage), "patchPostfixSave");

            Patches info = harmony.IsPatched(originalSave);
            if (info == null)
            {
                harmony.Patch(originalSave, new HarmonyMethod(prefixSave), new HarmonyMethod(postfixSave));
            }
        }

        protected override void Initialize()
        {
            base.Initialize();

            //Initialize lock object
            saveLock = new object();

            // Get log
            log = GetService(typeof(SVsActivityLog)) as IVsActivityLog;

            // Hard reference needs to be kept to Events and DocumentEvents in order for GC not to collect it.
            dte = (DTE)GetService(typeof(SDTE));
            events = dte.Events;
            documentEvents = events.DocumentEvents;
        }

        public static void patchPrefixSave(Microsoft.BizTalk.Mapper.OM.Map __instance, string __state, ref string strPath)
        {
            string originalPath = strPath;
        }

        public static void patchPostfixSave(Microsoft.BizTalk.Mapper.OM.Map __instance, string __state, ref string strPath)
        {
            string originalPath = strPath;
        }
```

```
System.NotSupportedException occurred
  HResult=-2146233067
  Message=Wrong MethodAttributes or CallingConventions for DynamicMethod. Only public, static, standard supported
  Source=mscorlib
  StackTrace:
       at System.Reflection.Emit.DynamicMethod.CheckConsistency(MethodAttributes attributes, CallingConventions callingConvention)
       at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod, StackCrawlMark& stackMark)
       at System.Reflection.Emit.DynamicMethod..ctor(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
       at Harmony.DynamicTools.CreateDynamicMethod(MethodBase original, String suffix)
       at Harmony.MethodPatcher.CreatePatchedMethod(MethodBase original, List`1 prefixes, List`1 postfixes, List`1 transpilers)
       at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
       at Harmony.PatchProcessor.Patch()
       at Harmony.HarmonyInstance.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler)
       at BizTalkFileFormatterV2015.VSPackage.InitializeSaveHook() in C:\git\biztalkfileformatter\BizTalkFileFormatter\BizTalkFileFormatterV2015\VSPackage.cs:line 73
  InnerException: 

```

**Comment by pardeike** [comment] 2018-04-15 18:45
Duplicate of #2

**Closed by pardeike** 2018-04-15 18:45 UTC
