### ISSUE TITLE
Have a Dictionary<string, object> __x parameter?

### ISSUE THREAD

**Issue by i00** [pardeike/Harmony#440] opened 2021-12-16 06:49 UTC
Hi ..
Great work, but I have come across a situation where I want to use this across all constructors within a certain namespace and "do stuff" automatically where I have a certain attribute on a parameter.
The issue is, since the number of parameters is unknown, I cannot seem to work out a way to capture these!

I suggest having an **ALL_PARAMS_PARAM = "__x"** ... so that a parameter **Dictionary<string, object> __x** can be used to capture all parameters in one single simple object.

Thanks

**Comment by pardeike** [comment] 2021-12-16 07:07
This was discussed before and the implementation has too many risks and downsides. There is the boxing problem and also questions on out or ref arguments. And then it would not be very fast with the risk of people using it and not understanding the implications. 

Therefore I am rather against such a high level feature. Instead you or some else would need to write a transpiler or a helper for a transpiler that does what you want.

**Comment by pardeike** [comment] 2021-12-29 19:56
Update: I am working on implementing `object __args` so I close this as a duplicate of https://github.com/pardeike/Harmony/issues/25

**Closed by pardeike** 2021-12-29 19:56 UTC
Labels: wontfix
