### ISSUE TITLE
(Mac/Linux) RimWorld crashes with Postfix on Window.PreClose

### ISSUE THREAD

**Issue by KiameV** [pardeike/Harmony#57] opened 2017-12-16 19:51 UTC
In one of my mods I was patching Window.PreClose to catch the event when a trade window closed (just patching Dialog_Trade.PreClose was not enough as it was not triggered when the user hit "esc" key to close the window)

```
    [HarmonyPatch(typeof(Window), "PreClose")]
    static class Patch_Window_PreClose
    {
        // Before closing any window
        static void Postfix(Window __instance)
        {
            Type type = __instance.GetType();
            if (type == typeof(Dialog_Trade))
            {
                TradeUtil.ReclaimApparel();
            }
        }
    }
```
I first tried removing the body to see if that fixed anything, it did not. So the simple act of adding this patch will cause RW to crash without any notice.

To reproduce, launch RW and try to close any window (even the console window) and it will cause the game to crash.

Just for clarification: This works fine on Windows 10. It does not work on Mac or Ubuntu.

**Comment by rheirman** [comment] 2018-02-09 14:10
I had exactly the same issue when I tried patching MentalState.PostStart. 
Both MentalState.PostStart and Window.PreClose are virtual methods, so I expect that the problem occurs when virtual methods are patched. This issue can easily be overlooked by modders as it doesn't cause problems on Windows machines, so I'm afraid the impact is quite big.

**Comment by pardeike** [comment] 2018-02-09 16:29
If this problem is in fact specific to virtual methods on everything non-Windows I need to look into a way to fix it. It could be a limitation on the CIL architecture.

**Comment by scuba156** [comment] 2018-02-10 11:39
Window.ExtraOnGUI() also crashes which is also virtual.

I did some testing. I can get these patches to work fine if there is only one patch applied, but will crash as soon as you add any other patch.

[Here is a log](https://pastebin.com/Vym8xWvN) from using ExtraOnGUI and PreClose for Page_ModsConfig, with the crash triggering when closing the console window.

**Comment by pardeike** [comment] 2018-03-31 12:41
I'm closing this. Cannot reproduce with the latest version. Tested on my Mac with the latest macos and latest Rimworld version with Window.PreClose() double patched.

**Closed by pardeike** 2018-03-31 12:41 UTC

**Comment by scuba156** [comment] 2018-04-01 13:05
Still an issue here. I can reproduce the crash, but I can also reproduce it working (kind of). This might be a long post as I'm just going to dump all the info I have here for now.

First off, all my patches are specifically patching Page_ModsConfig methods and are postfix's as this is what my target is, but I can reproduce it for any window. Patching Window directly gives the same results.

Second, the same happens with Window.ExtraOnGUI() in place of PreClose().

I tested in a new test project, this is the only code executed in my main class:
```
public class Main : Mod
    {
        public Main(ModContentPack content) : base(content)
        {
            Log.Message(string.Format("Starting {0}", content.Name));
            var harmonyInstance = HarmonyInstance.Create("com.scuba156.Harmony_Crash_Test");
            harmonyInstance.PatchAll(Assembly.GetExecutingAssembly());

            foreach (var patchedMethod in harmonyInstance.GetPatchedMethods())
            {
                Log.Message(string.Format("Patched {0}", patchedMethod.Name));
            }

            Log.Message("Everything is loaded, ready to crash!");
        }
    }
```

Each patch just outputs a line to the log when it is called. Below is an example of my PreClose patch:
```
    [HarmonyPatch]
    [HarmonyPatch(typeof(Page_ModsConfig))]
    [HarmonyPatch("PreClose")]
    public static class PreClose_Patch {

        public static void Postfix(this Page_ModsConfig __instance) {
            Log.Message("PreClose Postfix called");
        }
    }
```

To reproduce a non-working example:
* At least 2 patches are needed. I used Window.PreOpen() as the other patch.
* Add the PreClose() patch to the project **AFTER** adding the PreOpen() patch
* All compiles will now crash when closing any window
* [Here is a log of this specific situation with PreClose()](https://pastebin.com/gxJh77JS)
* [Here is a log of this specific situation with ExtraOnGUI()](https://pastebin.com/kHg6rHhT)

To reproduce a semi-working example:
* Have only a single patch **OR** add the PreClose() patch to the project **BEFORE** adding the PreOpen() patch
* All compiles will now load without crashing, but still do not work as expected. For example, PreClose will be called on any window close, but PreOpen will only be called when Page_ModsConfig opens, with the latter being the expected behaviour.
* [Here is a log of this specific situation with PreClose() (Notice how many times PreClose is called compared to PreOpen)](https://pastebin.com/2ngUmE3J)
* [Here is a log of this specific situation with ExtraOnGUI() (The patch is being called on every Window.ExtraOnGUI rather than only on Page_ModsConfig.ExtraOnGUI)](https://pastebin.com/YLxfXCae)

Note the order that the patches are loaded in each log. I would suspect that the crash would also be reproduced by manually patching each method in a specific order rather than adding them to the project in a specific order and using PatchAll(). I haven't tested this as I'm too lazy to do it right now. I can later on though. This was all tested on Linux Mint 18.3 compiled with MonoDevelop 7.4. The same issue was previously tested on Ubuntu and OS X compiled with Visual Studio on Windows 10

**Comment by pardeike** [comment] 2018-04-01 15:15
Harmony only patches methods where there is a real method with IL code in the assembly. `Page_ModsConfig` has no `PreClose` and therefore you cannot patch it.

**Comment by pardeike** [comment] 2018-04-01 15:17
As a follow up, I am going to make sure you can only patch **declared** methods and let Harmony throw a "method not found" error when the method isn't implemented in the class you specify.

**Comment by scuba156** [comment] 2018-04-01 15:35
As I said, "Patching Window directly gives the same results." and "I can reproduce it for any window."

While you are correct about the inheritance, and I did not have the chance to look directly at the source today to see if Page_ModsConfig actually exists, the CTD will still occur regardless.

**Comment by pardeike** [comment] 2018-04-01 15:38
Something funky goes on. I am currently testing to patch .NET 4+ classes to test Harmony and I get several cases where the patch order matters or else it crashes hard. Quite tricky to debug since it involves undocumented mono/NET API.
