### ISSUE TITLE
Arithmetic overflow crashing host process

### ISSUE THREAD

**Issue by apobekiaris** [pardeike/Harmony#297] opened 2020-05-25 13:41 UTC
I am using a recompiled for net461 version at cceb7f5e8176da14a2222800114dd44100e25e80 15 days ago and when my patched assemblies are loaded from VS (x86) the process crash

![image](https://user-images.githubusercontent.com/159464/82817513-c8919d00-9ea5-11ea-9211-847de5501f44.png)

switching back to 277c77bfa3c0a667cfe8d905956caf39726068a8 where monomod was not introduced i do not get any issues.

**Comment by pardeike** [comment] 2020-05-25 15:12
Not enough information about your related patches. Adding @0x0ade anyway.

**Comment by apobekiaris** [comment] 2020-05-25 15:28
i am not sure what type of info is helpfull my patches are super simple 

```cs
internal static partial class RxApp{
        static void CreateFrame(Frame __result){
            FramesSubject.OnNext(__result);
        }
    }
```
the initialization is 
```cs
         var xafApplicationMethods = typeof(XafApplication).Methods();
            var createFrameMethodPatch = GetMethodInfo(nameof(CreateFrame));
            var frameMethods = new[]{
                xafApplicationMethods.First(info => info.Name == nameof(XafApplication.CreateNestedFrame)),
                xafApplicationMethods.First(info => info.Name == nameof(XafApplication.CreateFrame))
            };
            foreach (var frameMethod in frameMethods){
                harmony.Patch(frameMethod, finalizer: new HarmonyMethod(createFrameMethodPatch));
            }
```

and the methods i patch are 

```cs
		public NestedFrame CreateNestedFrame(ViewItem detailViewItem, TemplateContext context) {
			return CreateNestedFrame(detailViewItem, context, null);
		}
		public Frame CreateFrame(TemplateContext context) {
			return new Frame(this, context, CreateControllers(typeof(Controller), true, null));
		}
```
also forgot to mention that the assemblies load fine with testrunners winapps and asp.net apps

if something else can help happy to provide

**Comment by pardeike** [comment] 2020-05-25 15:37
Have you tried to replicate with a version build from master? There have been changes lately to MonoMod.Common and it helps to get the baseline. You can even try to clone master and go into Harmony.csproj and use the latest MonoMod.Common Version to build to make sure we are not dealing with an issue that is fixed and that is caused by me not keeping up with the lastest MMC updates.

**Comment by apobekiaris** [comment] 2020-05-25 15:41
although I am only 15 days back on both Harmony and MonoMod repos I will rebuild the latest and update u

**Comment by 0x0ade** [comment] 2020-05-25 15:41
It probably won't be caused by any patches in particular, but the environment you're patching in.

> are loaded from VS (x86)

By chance, do you know if the process you're patching in is large address aware?  
And if you're replicating it consistently, can you please provide `from` and `delta` as well?

**Comment by apobekiaris** [comment] 2020-05-25 16:15
hmm yeah it's not consistent probably scared of u guys, i let u know soon though cause is often.

>By chance, do you know if the process you're patching in is large address aware?

i am not experience in this level but considering that my patching process should be the devenv.exe cause I am loading the assemblies thtough VS combonent designer are u looking for something like  this https://stackoverflow.com/questions/9054469/how-to-check-if-exe-is-set-as-largeaddressaware/9056757

**Comment by 0x0ade** [comment] 2020-05-25 19:10
I've just pushed a possible fix for this issue to the MonoMod.Common repository: https://github.com/MonoMod/MonoMod.Common/commit/1498092bdc357bcdfefac8d91356fc06a2a26bcb

MonoMod.Common 20.5.25.1 should be available on nuget.org shortly, after which either Harmony will need to update to it, or you'll need to build Harmony with that update yourself.

**Comment by pardeike** [comment] 2020-05-25 20:51
Now master uses 20.5.25.1. @apobekiaris can you build it and test to verify the fix?

**Comment by apobekiaris** [comment] 2020-05-26 02:00
thnks will do, fyi the reason I get into trouble recompiling both repos is that assemblies are not strongly signed, hopefully at some point u will reconsider this decision

**Comment by pardeike** [comment] 2020-05-26 04:32
The decision on signing framework and libraries like Harmony was discussed before (and even tested!) and it causes more problems than it solves. In the end it was concluded that users like you need to resign it themselves with the appropriate tools.

**Comment by apobekiaris** [comment] 2020-05-26 04:35
yeah I am aware of it, however it super easy to sing if there are no unsigned dependencies like MonoMod but if there are u need to recompile or patch the references.

**Comment by pardeike** [comment] 2020-05-26 04:43
If your requirements are for things to be signed you probably want your own copy of repositories mirrored and build your binaries yourself. At least that’s what we do at my government job.

**Comment by apobekiaris** [comment] 2020-05-26 10:01
I now complied the latest Harmony for net461 and MonoMod for netstandard2.0 and although it never completes now the exception is different

![image](https://user-images.githubusercontent.com/159464/82887214-5cb83e80-9f50-11ea-95d8-dd63991f68e4.png)

i played around with the patched methods and I noticed that I can patch this method 
```cs
		protected internal virtual Frame CreateFrame(TemplateContext context, View view) {
			if(OptimizeControllersCreationInMasterDetailMode) {
				return new Frame(this, context, CreateControllers(typeof(Controller), true, null, view));
			}
			return new Frame(this, context, CreateControllers(typeof(Controller), true, null, null));
		}
```

but not this one
```cs
		private ApplicationModulesManager CreateModuleManager(String[] moduleAssemblies) {
			Tracing.Tracer.LogSubSeparator("Initialize Modules Manager");
			ApplicationModulesManager modulesManager = CreateApplicationModulesManager(CreateControllersManager());
			if(modulesManager == null) {
				throw new InvalidOperationException(SystemExceptionLocalizer.GetExceptionMessage(ExceptionId.TheCreateApplicationModulesManagerReturnsNull));
			}
			modulesManager.Modules = modules;
			foreach(Type moduleType in GetDefaultModuleTypes()) {
				modulesManager.AddModule(moduleType);
			}
			modulesManager.AddModuleFromAssemblies(moduleAssemblies);
			return modulesManager;
		}
```

and if i move the method to class that i own there are no errors.

**Comment by apobekiaris** [comment] 2020-05-26 10:04
method patch is done like

```cs
var harmonyMethod = new HarmonyMethod(GetMethodInfo(nameof(CreateModuleManager)));
harmony.Patch(createModuleManager, finalizer: harmonyMethod);
```

and redirection is defined as 
```cs
        static void CreateModuleManager(ApplicationModulesManager __result){
            ApplicationModulesManagerSubject.OnNext(__result);
        }

```

**Comment by apobekiaris** [comment] 2020-05-27 06:49
@0x0ade  I found which is the last Monomod working commit. If I compile latest Harmony commit against [Fix GetLdftnPointer, use it for virtual struct methods on .NET](58702d64645aba613ad16275c0b78278ff0d2055) it works however compiling against the next one ["Parse" some .NET JIT stubs, required to hook NGEN'd methods](dcd602e57ec4f50dc124eb7eb59c8c30f815c0ea)

**Comment by apobekiaris** [comment] 2020-06-04 04:22
Hello,

As all my published packages (100+) depends on harmony it is of a major importance to be able to follow the latest version. So I wonder should I expect some fix on this? or is it anything else that I can provide that could help?

**Comment by pardeike** [comment] 2020-06-07 10:11
I don't see how I can wait releasing Harmony 2.0.2 and have it contain a fix for this. So I am going to release 2.0.2 and we have to deal with this in a later version.

**Comment by apobekiaris** [comment] 2020-06-21 07:50
I am getting an arithmetic overflow again however this time is on runtime so unrelated to VS process and can share the repro sample.

[Solution15.zip](https://github.com/pardeike/Harmony/files/4809053/Solution15.zip)

```
Method virtual System.Object DevExpress.ExpressApp.Security.AuthenticationStandard::Authenticate(DevExpress.ExpressApp.IObjectSpace objectSpace) cannot be patched. Reason: Arithmetic operation resulted in an overflow.

   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at 
```


The patching is done XAfApplicationExtensions .cs file for the Authenticate method. The patching code I borrowed from another project of mine that works and is build for 4.7.2 as well, however Harmony used there is build against the commits I mentioned above.

The project uses Harmony.lib 2.0.1 from nuget.

**Comment by pardeike** [comment] 2020-06-21 19:13
I tested the project and when I start it, it shows a password login dialog. Is it crashing after or before that dialog comes up?

**Comment by apobekiaris** [comment] 2020-06-22 11:10
it throws b4 the dialog and  a not implemented exception on accept implies that the patch worked. Further testing unfortunately revealed that this exception is not consistent in all environments

**Comment by pardeike** [comment] 2020-12-31 19:08
Closed because of inactivity

**Closed by pardeike** 2020-12-31 19:08 UTC
Labels: bug, cannot reproduce, help wanted, needs more info/work
